github: [metadata]

remote_theme: mmistakes/minimal-mistakes@4.19.2
minimal_mistakes_skin: "contrast"

# Site settings
title:          "Michael's Dev Journal"
name:           "Michael Honke"
description:    "I enjoy modelling systems and playing with them in a virtual world to see how they match reality. What I share here is for my amusement. It might be a game, simulation or just something interesting."
baseurl:        "" # the subpath of your site, e.g. /blog
url:            "https://mlhonke.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
    email: "mlhonke@uwaterloo.ca"
    name: "Michael Honke"
    links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mlhonke"


plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
