github: [metadata]

# includes
include: ["_pages"]

# select theme depending if hosting locally or on GitHub
remote_theme: mmistakes/minimal-mistakes@4.19.2
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

# Site settings
locale:         "en-US"
title:          "Michael's R&D Journal"
name:           "Michael Honke"
description:    "I enjoy modelling systems and playing with them in a virtual world to see how they match reality. What I share here is for my amusement. It might be a game, simulation or just something interesting."
baseurl:        "" # the subpath of your site, e.g. /blog
url:            "https://mlhonke.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository:     "mlhonke/mlhonke.github.io"
# teaser:         
search:         true


# Author settings
author:
    name: "Michael Honke"
    email: "mlhonke@uwaterloo.ca"
    avatar: "assets/images/mhonke3_compressed.jpg"
    #    bio: "I work at the intersection of <b>physics, math and computer science</b> researching <b> simulation, computer graphics and AI"
    links:
    #- label: "Facebook"
      #icon: "fab fa-fw fa-facebook-square"
      #url: "https://facebook.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michael-honke/"      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mlhonke"

# Site Footer
footer:
  links:
    #- label: "Facebook"
      #icon: "fab fa-fw fa-facebook-square"
      #url:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michael-honke/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mlhonke"
      
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
      
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
    
# Sass/SCSS
sass:
 sass_dir: _sass
#  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
    
# Outputting
#permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
    
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment   
    
collections:
  projects:
    output: true
    permalink: /:collection/:path/
    
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
